# mybatis settings
mybatis:
  mapper-locations: "classpath:/mybatis/mapper/*.xml"

spring:
  thymeleaf:
    suffix: .html
  jpa:
    database-platform: org.hibernate.spatial.dialect.mariadb.MariaDB103SpatialDialect
    properties:
      hibernate:
        '[format_sql]': true
        ddl-auto: create #validate
        '[physical_naming_strategy]': org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false

---

#local db info
spring:
  config:
    activate:
      on-profile: local
  mvc:
    view:
      suffix: .html

  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ENC(SgN23c3fqhNdxm80w1Hj7g==)
        password: ENC(5Gs0BJ7jgRQRMBAmF+r7J9vT7KFLtKEl)
        url: ENC(sHIcuTnT8IWPgh6tnjbL3ZYaW81GFwqTwGSUr31mrxIW5me16lgH5fCdjRYxBk5nsQMpSvVzksytKYyJgM/URY9oBrB3HMeH)

